[theme]
primaryColor = "#00f5ff"
backgroundColor = "#0c0c0c"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#e0e6ed"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
